services:
  api:
    build: .
    # restart: always
    depends_on:
      - postgres_db
    ports:
      - 3000:3000
    command: npm run start:dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - poste_man
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}

      - POSTGRES_PASSWORD_TEST=${POSTGRES_PASSWORD_TEST}
      - POSTGRES_USER_TEST=${POSTGRES_USER_TEST}
      - POSTGRES_DB_TEST=${POSTGRES_DB_TEST}
      - DATABASE_URL_TEST=${DATABASE_URL_TEST}

      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
      - JWT_SECRET=${JWT_SECRET}

      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SERVER_URL=${SERVER_URL}

      - FRONT_URL=${FRONT_URL}
      - IS_PRODUCTION=${IS_PRODUCTION}
      - PORT_GATEWAY=${PORT_GATEWAY}

  postgres_db:
    image: postgres:17.7-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    networks:
      - poste_man

  test_db:
    image: postgres:17.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - '5435:5432'
    networks:
      - poste_man

networks:
  poste_man:
    external: true

volumes:
  postgres-data:
